package org.latin.verb;

public enum Position {
	FIRST_PERSON_SINGULAR_PRESENT (BuiltWith.BASIS_PRESENT),	FIRST_PERSON_PLURAL_PRESENT (BuiltWith.BASIS_PRESENT),
	SECOND_PERSON_SINGULAR_PRESENT(BuiltWith.BASIS_PRESENT),	SECOND_PERSON_PLURAL_PRESENT(BuiltWith.BASIS_PRESENT),
	THIRD_PERSON_SINGULAR_PRESENT (BuiltWith.BASIS_PRESENT),	THIRD_PERSON_PLURAL_PRESENT (BuiltWith.BASIS_PRESENT),
	
	SECOND_PERSON_SINGULAR_IMPERATIVE(BuiltWith.BASIS_PRESENT),	SECOND_PERSON_PLURAL_IMPERATIVE(BuiltWith.BASIS_PRESENT),
	
	FIRST_PERSON_SINGULAR_IMPERFECT(BuiltWith.BASIS_PRESENT),	FIRST_PERSON_PLURAL_IMPERFECT(BuiltWith.BASIS_PRESENT),
	SECOND_PERSON_SINGULAR_IMPERFECT(BuiltWith.BASIS_PRESENT),	SECOND_PERSON_PLURAL_IMPERFECT(BuiltWith.BASIS_PRESENT),
	THIRD_PERSON_SINGULAR_IMPERFECT(BuiltWith.BASIS_PRESENT),	THIRD_PERSON_PLURAL_IMPERFECT(BuiltWith.BASIS_PRESENT),
	
	FIRST_PERSON_SINGULAR_FUTUR_I(BuiltWith.BASIS_PRESENT),		FIRST_PERSON_PLURAL_FUTUR_I(BuiltWith.BASIS_PRESENT),
	SECOND_PERSON_SINGULAR_FUTUR_I(BuiltWith.BASIS_PRESENT),		SECOND_PERSON_PLURAL_FUTUR_I(BuiltWith.BASIS_PRESENT),
	THIRD_PERSON_SINGULAR_FUTUR_I(BuiltWith.BASIS_PRESENT),		THIRD_PERSON_PLURAL_FUTUR_I(BuiltWith.BASIS_PRESENT),
	
	FIRST_PERSON_SINGULAR_PERFECT(BuiltWith.BASIS_PERFECT),		FIRST_PERSON_PLURAL_PERFECT(BuiltWith.BASIS_PERFECT),
	SECOND_PERSON_SINGULAR_PERFECT(BuiltWith.BASIS_PERFECT),		SECOND_PERSON_PLURAL_PERFECT(BuiltWith.BASIS_PERFECT),
	THIRD_PERSON_SINGULAR_PERFECT(BuiltWith.BASIS_PERFECT),		THIRD_PERSON_PLURAL_PERFECT(BuiltWith.BASIS_PERFECT),
	
	FIRST_PERSON_SINGULAR_PLUS_QUAM_PERFECT(BuiltWith.BASIS_PERFECT),	FIRST_PERSON_PLURAL_PLUS_QUAM_PERFECT(BuiltWith.BASIS_PERFECT),
	SECOND_PERSON_SINGULAR_PLUS_QUAM_PERFECT(BuiltWith.BASIS_PERFECT),	SECOND_PERSON_PLURAL_PLUS_QUAM_PERFECT(BuiltWith.BASIS_PERFECT),
	THIRD_PERSON_SINGULAR_PLUS_QUAM_PERFECT(BuiltWith.BASIS_PERFECT),	THIRD_PERSON_PLURAL_PLUS_QUAM_PERFECT(BuiltWith.BASIS_PERFECT),
	
	FIRST_PERSON_SINGULAR_FUTUR_II(BuiltWith.BASIS_PERFECT),		FIRST_PERSON_PLURAL_FUTUR_II(BuiltWith.BASIS_PERFECT),
	SECOND_PERSON_SINGULAR_FUTUR_II(BuiltWith.BASIS_PERFECT),	SECOND_PERSON_PLURAL_FUTUR_II(BuiltWith.BASIS_PERFECT),
	THIRD_PERSON_SINGULAR_FUTUR_II(BuiltWith.BASIS_PERFECT),		THIRD_PERSON_PLURAL_FUTUR_II(BuiltWith.BASIS_PERFECT),
	
	FIRST_PERSON_SINGULAR_PASSIVE_PRESENT(BuiltWith.BASIS_PRESENT),		FIRST_PERSON_PLURAL_PASSIVE_PRESENT(BuiltWith.BASIS_PRESENT),
	SECOND_PERSON_SINGULAR_PASSIVE_PRESENT(BuiltWith.BASIS_PRESENT),		SECOND_PERSON_PLURAL_PASSIVE_PRESENT(BuiltWith.BASIS_PRESENT),
	THIRD_PERSON_SINGULAR_PASSIVE_PRESENT(BuiltWith.BASIS_PRESENT),		THIRD_PERSON_PLURAL_PASSIVE_PRESENT(BuiltWith.BASIS_PRESENT),
	
	FIRST_PERSON_SINGULAR_PASSIVE_IMPERFECT(BuiltWith.BASIS_PRESENT),		FIRST_PERSON_PLURAL_PASSIVE_IMPERFECT(BuiltWith.BASIS_PRESENT),
	SECOND_PERSON_SINGULAR_PASSIVE_IMPERFECT(BuiltWith.BASIS_PRESENT),		SECOND_PERSON_PLURAL_PASSIVE_IMPERFECT(BuiltWith.BASIS_PRESENT),
	THIRD_PERSON_SINGULAR_PASSIVE_IMPERFECT(BuiltWith.BASIS_PRESENT),		THIRD_PERSON_PLURAL_PASSIVE_IMPERFECT(BuiltWith.BASIS_PRESENT),
	
	FIRST_PERSON_SINGULAR_PASSIVE_FUTUR_I(BuiltWith.BASIS_PRESENT),		FIRST_PERSON_PLURAL_PASSIVE_FUTUR_I(BuiltWith.BASIS_PRESENT),
	SECOND_PERSON_SINGULAR_PASSIVE_FUTUR_I(BuiltWith.BASIS_PRESENT),		SECOND_PERSON_PLURAL_PASSIVE_FUTUR_I(BuiltWith.BASIS_PRESENT),
	THIRD_PERSON_SINGULAR_PASSIVE_FUTUR_I(BuiltWith.BASIS_PRESENT),		THIRD_PERSON_PLURAL_PASSIVE_FUTUR_I(BuiltWith.BASIS_PRESENT);
	
	private BuiltWith builtWith;
	
	private Position(BuiltWith builtWith) { this.builtWith = builtWith; }
	
	public BuiltWith builtWith() { return builtWith; }
}
